services:
   Aldaflux\AldafluxUserRoleTypeBundle\DataCollector\UserRoleTypeCollector:
        tags:
            -
                name:     data_collector
                id:       'aldaflux.user_role_type_collector'
   aldaflux_user_role_type.form.user_role_type:
        class: Aldaflux\AldafluxUserRoleTypeBundle\Form\Type\UserRoleType
        arguments: ['@security.role_hierarchy', "@security.helper", "@parameter_bag"]
        tags: [form.type]
